name: Main Workflow
on: [ push, pull_request ]
env:
  LLVM_VERSION: 19
jobs:
  debug:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container: ghcr.io/opencyphal/toolshed:ts24.4.3
    strategy:
      matrix:
        toolchain: [ "clang", "gcc" ]
        include:
          - toolchain: gcc
            c-compiler: gcc
            cxx-compiler: g++
          - toolchain: clang
            c-compiler: clang
            cxx-compiler: clang++
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # language=bash
      - run: >
          cmake
          -B $GITHUB_WORKSPACE/build
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=${{ matrix.c-compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx-compiler }}
          .
      # language=bash
      - run: |
          cd $GITHUB_WORKSPACE/build
          make VERBOSE=1 -j$(nproc)
          make test ARGS="--verbose"
      - name: Archive workspace
        if: always()
        run: |
          cd $GITHUB_WORKSPACE
          tar --use-compress-program="gzip -9" -cf $RUNNER_TEMP/workspace.tar.gz .
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          # The matrix is shown for convenience but this is fragile because the values may not be string-convertible.
          # Shall it break one day, feel free to remove the matrix from here.
          name: ${{github.job}}-#${{strategy.job-index}}-${{job.status}}-${{join(matrix.*, ',')}}
          path: ${{runner.temp}}/workspace.tar.gz
          retention-days: 2

  optimizations:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container: ghcr.io/opencyphal/toolshed:ts24.4.3
    strategy:
      matrix:
        toolchain: [ "clang", "gcc" ]
        build_type: [ Release, MinSizeRel ]
        include:
          - toolchain: gcc
            c-compiler: gcc
            cxx-compiler: g++
            cxx-flags: ""
          - toolchain: clang
            c-compiler: clang
            cxx-compiler: clang++
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # language=bash
      - run: >
          cmake
          -B $GITHUB_WORKSPACE/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.c-compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx-compiler }}
          -DCMAKE_CXX_FLAGS="${{ matrix.cxx-flags }}"
          -DNO_STATIC_ANALYSIS=1
          .
      # language=bash
      - run: |
          cd $GITHUB_WORKSPACE/build
          make VERBOSE=1 -j$(nproc)
          make test ARGS="--verbose"
      - name: Archive workspace
        if: always()
        run: |
          cd $GITHUB_WORKSPACE
          tar --use-compress-program="gzip -9" -cf $RUNNER_TEMP/workspace.tar.gz .
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          # The matrix is shown for convenience but this is fragile because the values may not be string-convertible.
          # Shall it break one day, feel free to remove the matrix from here.
          name: ${{github.job}}-#${{strategy.job-index}}-${{job.status}}-${{join(matrix.*, ',')}}
          path: ${{runner.temp}}/workspace.tar.gz
          retention-days: 2

  coverage:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container: ghcr.io/opencyphal/toolshed:ts24.4.3
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # language=bash
      - run: >
          cmake -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=Debug -DNO_STATIC_ANALYSIS=ON -DENABLE_COVERAGE=ON .
      # language=bash
      - run: |
          cd $GITHUB_WORKSPACE/build
          make -j$(nproc) && make test && make coverage
      - name: Archive workspace
        if: always()
        run: |
          cd $GITHUB_WORKSPACE
          tar --use-compress-program="gzip -9" -cf $RUNNER_TEMP/workspace.tar.gz .
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{github.job}}-#${{strategy.job-index}}-${{job.status}}
          path: ${{runner.temp}}/workspace.tar.gz
          retention-days: 30

  # TODO: re-enable this
  #  avr:
  #    if: github.event_name == 'push'
  #    runs-on: ubuntu-latest
  #    env:
  #      mcu: at90can64
  #      flags: -Wall -Wextra -Werror -pedantic -Wconversion -Wtype-limits
  #    strategy:
  #      matrix:
  #        std: [ 'c99', 'c11', 'gnu99', 'gnu11' ]
  #    steps:
  #      - uses: actions/checkout@v4
  #      # language=bash
  #      - run: |
  #          sudo apt update -y && sudo apt upgrade -y
  #          sudo apt install gcc-avr avr-libc
  #          avr-gcc --version
  #      - run: avr-gcc -Ilib/cavl/ libudpard/*.c -c -std=${{matrix.std}} -mmcu=${{env.mcu}} ${{env.flags}}

  arm:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      flags: -Wall -Wextra -Werror -pedantic -Wconversion -Wtype-limits -Wcast-align -Wfatal-errors
    strategy:
      matrix:
        std: [ "c99", "c11", "gnu99", "gnu11" ]
    steps:
      - uses: actions/checkout@v4
      # language=bash
      - run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt-get install -y gcc-arm-none-eabi
      - run: arm-none-eabi-gcc -Ilib/cavl/ libudpard/*.c -c -std=${{matrix.std}} ${{ env.flags }}

  style_check:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "./libudpard ./tests"
          extensions: "c,h,cpp,hpp"
          clangFormatVersion: ${{ env.LLVM_VERSION }}
